Changelog.md, bin/dotenv, spec/dotenv/bin_spec.rb
allow specifying which `.env` files to use
```console
dotenv -f /path/to/.env,/path/to/another/.env
```
comes with tests
=> Support -f option to dotenv binary

lib/dotenv/parser.rb, spec/dotenv/parser_spec.rb
some people want to declare vars and then export them like this:
SOME=thing
export SOME
this pull request will allow that and even validate that the var is set
=> allow export line

lib/dotenv.rb, spec/dotenv_spec.rb
- Add `overload` test coverage for missing files.
- Ignore nonexistent file errors as they happen instead of trying to guard for them.
Checking for file existence before reading is prone to race conditions where the file in question is removed in between checking for it and reading it. A more viable approach is to ignore the exception for when it does not exist.
=> Ignore nonexistent files

Changelog.md, Gemfile, dotenv-rails.gemspec, lib/dotenv/version.rb
https://github.com/bkeepers/dotenv/pull/159 adds back support for `.env.#{Rails.env}` that was removed in /cc https://github.com/bkeepers/dotenv/pull/95, so I'm going to bump the major version to indicate the change in functionality and push out a beta release to make sure there are no major issues with it.
Once this is released, I will probably deprecate the `dotenv-deployment` gem (or see if someone else wants to maintain it).
=> Prepare for 2.0 beta release

lib/dotenv/substitutions/variable.rb, spec/dotenv/parser_spec.rb
Previously this fails:
``` ruby
Variable.call("${FOO} \\${FOO} ${FOO}", "FOO" => "BAR") #=> "BAR BAR ${FOO}"
```
=> Expand variables correctly

Guardfile, dotenv.gemspec
Fixes `Use %r around regular expression`
=> Fix `rubocop` warnings

dotenv-rails.gemspec
As dotenv-rails doesn't currently depend on rails 4 apart from in development, my gemspecs are pulling it in automatically in rails 3 apps. Obviously, I will fix my own bundle, but it seems that dotenv-rails should be linked to rails itself as a full dependency.
=> Make dotenv-rails depend on rails 4 in production

lib/dotenv/parser.rb, spec/dotenv/parser_spec.rb
Carriage return is used in Mac OS.
Currently, if the .env file is like that (`\r` is the newline char in Mac):
api_key=foo\r
another_token=bar
then it would be parsed as: `api_key=foo\ranother_token=bar`
=> supporting carriage return

Changelog.md, lib/dotenv/version.rb
* #194: supporting carriage return - @flyfy1
* #193: Add a Gitter chat badge to README.md - @gitter-badger
* #189: Make dotenv-rails depend on rails 4 in production - @Floppy
* #184: Feature/improve clarity of multiple env docs - @conorliv
* #182: Remove conflict marker - @teoljungberg
* #183: Fix `rubocop` warnings - @teoljungberg
=> Prepare for 2.0.2 release

dotenv.gemspec
Fix ordering in gemspec from e13bf8a877e2237b1c91c66c775f88bbcaafe314.
/cc @replaid
=> Fix ordering of executables in gemspec

spec/dotenv/parser_spec.rb
If the specs are being run with a different version of ruby than the one in the path, then this spec will fail. This simplifies it by just calling echo to test command interpolation.
Closes #210
/cc @terceiro
=> don't assume `ruby`

lib/dotenv/substitutions/variable.rb, spec/dotenv/parser_spec.rb
The issue was that the regex was not capturing $ which are not followed by alphanumericals. So, cases like "BAR\$" and "\$\$" were not handled. 
Made changes to take care of these.
=> Fix for #207, Some escaped '$' characters are not unescaped

Guardfile, dotenv-rails.gemspec, dotenv.gemspec, lib/dotenv.rb, lib/dotenv/environment.rb, lib/dotenv/parser.rb, lib/dotenv/version.rb, spec/dotenv/rails_spec.rb, spec/dotenv_spec.rb
Fix the following offenses.
```
$ bundle exec rubocop  
Inspecting 23 files
CC.C...CC.....C.C...CC.
Offenses:
dotenv-rails.gemspec:11:5: C: Align .split with git ls-files lib | grep rails on line 10.
.split($OUTPUT_RECORD_SEPARATOR) + ["README.md", "LICENSE"]
^^^^^^
dotenv.gemspec:12:5: C: Align .split with git ls-files README.md LICENSE lib bin | grep -v rails on line 11.
.split($OUTPUT_RECORD_SEPARATOR)
^^^^^^
dotenv.gemspec:13:36: C: Use %r around regular expression.
gem.executables = gem.files.grep(/^bin\//).map { |f| File.basename(f) }
^^^^^^^^
Guardfile:6:9: C: Use %r around regular expression.
watch(/^spec\/.+_spec\.rb$/)
^^^^^^^^^^^^^^^^^^^^^
Guardfile:7:9: C: Use %r around regular expression.
watch(/^spec\/spec_helper.rb$/) { "spec" }
^^^^^^^^^^^^^^^^^^^^^^^^
Guardfile:8:9: C: …
```
=> Fix Rubocop offenses

.travis.yml, Rakefile, dotenv.gemspec
This locks the version of rubocop to prevent offenses from randomly cropping up. /cc #239 #230 #183
=> Lock rubocop

.travis.yml
#233 is caused by a bug the latest release in jruby. It's fixed upstream, but currently causing the build to fail. This updates travis to allow failures on `jruby-head` for now.
=> Allow failures for jruby-head until next release

lib/dotenv/rails.rb
I'm currently working a project that is a [Rails engine](http://guides.rubyonrails.org/engines.html)
When I add `dotenv-rails` to my `Gemfile`, and try to run a command, say: `bundle exec rspec spec`, this error occurs:
```
{gem-path}/spring-1.6.4/lib/spring/configuration.rb:31:in `application_root_path':
Spring was unable to find your config/application.rb file.
Your project root was detected at {project-root}, so spring looked
for {project-root}/config/application.rb but it doesn't exist.
You can configure the root of your application by
setting Spring.application_root in config/spring.rb. (Spring::MissingApplication)
from {gem-path}/spring-1.6.4/lib/spring/watcher.rb:24:in `watcher`
```
The error is saying that Spring can't find my `application_root`. This is odd, because [Spring …
=> Fix load error when using Spring w/ custom config

lib/dotenv/parser.rb
Fix the following failure spec.
```sh
$ ruby -v
ruby 2.4.0dev (2016-03-23 trunk 54236) [x86_64-darwin13]
$ bundle exec rake spec
.............................................F..........................
Failures:
1) Dotenv::Parser substitutes shell variables within interpolated shell commands
Failure/Error:
expect(env(%(VAR1=var1\ninterp=$(echo "VAR1 is $VAR1")))["interp"])
.to eql("VAR1 is var1")
expected: "VAR1 is var1"
got: "VAR1 is "
(compared using eql?)
Finished in 0.16655 seconds (files took 0.62432 seconds to load)
72 examples, 1 failure
Failed examples:
rspec ./spec/dotenv/parser_spec.rb:171 # Dotenv::Parser substitutes shell variables within interpolated shell commands
```
Module#constants method makes NO guarantees about the order in which the constants are yielded. Then order …
=> Fix a failure spec in ruby 2.4.0dev

dotenv.gemspec
This pull request fix the following deprecation warning.
```sh
% bundle exec rake
[DEPRECATION] `last_comment` is deprecated.  Please use `last_description` instead.
```
This warning was resolved by upgrade to [Rubocop >= 0.38.0](https://github.com/bbatsov/rubocop/commit/88a200e59e10868450ceb4316ffc600d9a09b95c). Therefore, Rubocop has been changed to latest version 0.40.0 in this PR.
=> Fix deprecation warning

dotenv-rails.gemspec, lib/dotenv/rails.rb
We are getting the following error when trying to use `require "dotenv/rails-now"`
> /Users/mikaelhenriksson/.rvm/gems/ruby-2.1.8/gems/activesupport-3.2.22.6/lib/active_support/dependencies.rb:243:in `load': wrong number of arguments (0 for 1..2) (ArgumentError)
>	from /Users/mikaelhenriksson/.rvm/gems/ruby-2.1.8/gems/dotenv-rails-2.0.1/lib/dotenv/rails.rb:20:in `block in <class:Railtie>'
Reordering the file so that the methods are defined before using them fixes this problem. Our codebase is from 2005 so I am sure it could be fixed in other ways but this is verified to fix our problem.
**Note 1:** The errors on CI doesn't seem to be related to my changes.
**Note 2:** This works for us on a rails 3.2 project
=> Reorder to make the load method available

lib/dotenv/load.rb
So it can be used as:
``` ruby
require "dotenv/load"
```
as a shortcut for:
``` ruby
require "dotenv"
Dotenv.load
```
In similar fashion to Bundler's `bundler/setup` which requires bundler then calls `Bundler.setup`.
=> Add dotenv/load shortcut file

lib/dotenv/parser.rb, spec/dotenv/parser_spec.rb
Hi!
I encountered the following problem(underscore => space).
```
NOTIFY_SLACK_CHANNEL='#channel_name'__
=> "'"
```
I think that it is okay to allow spaces at the end of the line.
Thanks.
=> Allow following whitespace

.travis.yml
Fix a following build error on Travis CI.
https://travis-ci.org/bkeepers/dotenv/jobs/194667067
```sh
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.
can't modify frozen String
Gem files will remain installed in
/home/travis/.rvm/gems/ruby-2.4.0/gems/rainbow-2.2.1 for inspection.
Results logged to
/home/travis/.rvm/gems/ruby-2.4.0/extensions/x86_64-linux/2.4.0/rainbow-2.2.1/gem_make.out
An error occurred while installing rainbow (2.2.1), and Bundler cannot
continue.
Make sure that `gem install rainbow -v '2.2.1'` succeeds before bundling.
```
This PR solves the problem by using the latest RubyGems.
cf. https://github.com/sickill/rainbow/issues/48
Thanks.
=> Fix a build error on Travis CI by using latest RubyGems

.travis.yml
They've been failing for a while and in the `allowed_failures`. The jruby build takes significantly longer than the others, so this just removes them entirely.
=> Remove jruby and rbx builds

.rubocop.yml, Changelog.md, Gemfile, Guardfile, README.md, Rakefile, lib/dotenv.rb, lib/dotenv/rails-now.rb, lib/dotenv/tasks.rb, spec/dotenv_spec.rb
I saw this all over the project the :old => syntax, so I replaced
everything (with a script) with the new: syntax
```bash
$ find . -name \*.rb -exec perl -p -i -e 's/([^:]):(\w+)\s*=>/\1\2:/g' {} \;
```
Found that [here](http://effectif.com/ruby/update-your-project-for-ruby-19-hash-syntax)
EDIT:
Whoops, okay didn't noticed that you got rubocop so I updated the rubocop.yml and rerun rubocop using `rubocop -a`.
=> Update ruby hash syntax

lib/dotenv/rails.rb, spec/dotenv/rails_spec.rb
This pulls in changes from both #249 and #257 to support `.env.#{Rails.env}.local`. I'm not crazy about this change, but enough people have asked for it that I'll concede (but you can't make me document it…yet :trollface:).
=> Allow local per env

lib/dotenv/rails.rb
This feture costs 1 line of code, but give more freedom to users
=> allow loading env-specific locals for Rails

lib/dotenv/rails.rb, spec/dotenv/rails_spec.rb, spec/fixtures/.env.test.local
This allows customization of specific Rails environments, instead of having
.env.local override values for _all_ Rails environments, which is not always
desirable.
=> Also load .env.#{Rails.env}.local

lib/dotenv/rails.rb
This fixes #219, which causes Rails apps to always be initialized in development when being loaded from rake, by adding a hack that sets `RAILS_ENV=test` when `rake spec` is being run.
Rails [already includes a hack](https://github.com/rails/rails/blob/56ca2061df83a307943a0ffdfe6f5f4ed5846cf7/railties/lib/rails/test_unit/railtie.rb#L3-L5) like this, which will set `RAILS_ENV=test` when running `rake test`. This hack used to be loaded when requiring `rails/all`, but https://github.com/rails/rails/pull/10256 moved to to only be loaded when requiring `test_unit/railtie`. So, deally, rspec would copy this behavior when loading the [rspec railtie](https://github.com/rspec/rspec-rails/blob/master/lib/rspec-rails.rb).
I need to figure out a way to test this. I would appreciate any ideas for how …
=> Fix for rspec rake tasks initializing in development

README.md
Hi!
I am explaining the load order to someone and I think make the files load order as a standalone section is easier to share to someone.
Note I added one sentence in this Pull Request:
```
Finally loads the `.env.local` if presents.
```
Thanks!
[Preview The New Section](https://github.com/JuanitoFatas/dotenv/blob/69c8345f0d3716ad9398c398825d816ccbd39f3f/README.md#env-files-load-order).
=> Make Load Order as a standalone subsetion [ci skip]

spec/dotenv/parser_spec.rb
This is related to an issue opened on the go implementation (see https://github.com/joho/godotenv/issues/26) where I'm trying to maintain file level compatibility with this lib.
I had a user relying on this functionality but no test documenting it. I tested dotenv & bash and discovered it was consistent but unspecified/undocumented here. Adding a test to move the behaviour up from accidental to on purpose 😄
=> Specify existing behaviour for parsing empty values.

README.md
Just to keep it in ruby context. Because this could be a little confused for a freshman developer.
=> Changes script type

lib/dotenv/substitutions/variable.rb, spec/dotenv/parser_spec.rb
=> Existing variable takes precendence when performing substitution

lib/dotenv/parser.rb, spec/dotenv/parser_spec.rb
This makes dotenv play better with .env files that
do more than just set variables, e.g. defining aliases
and functions
closes #285
=> Skip over lines that don't set an envvars

lib/dotenv/parser.rb, spec/dotenv/parser_spec.rb
These minor changes allow for successfully parsing config variables exported from Heroku.
=> Parse multiline values

README.md
The `-f` flag for `dotenv` was not previously documented in the README. But now it is!
=> Document the -f flag

lib/dotenv/rails.rb
Resolves an issue where spring tries to `File.expand_path` and the
`$HOME` variable is not set.
This was identified as an issue with AWS Elastic Beanstalk deployments
=> Rescue from bundler require error

README.md
Version at a glance, so I don't need to check `Changelog.md` (which incidentally is out-of-sync with gem version because PR #327 hasn't been merged yet), or worse yet `lib/dotenv/version.rb`
=> Add gem version badge to README.md

lib/dotenv/parser.rb
#338 
Version 2.3 is not backward compatible with features such as `parser`
Therefore, since we made backwards compatibility for `parser`, I would like to confirm it
=> backward compatible to v2.2 as parser

Changelog.md
Since it is in another release section, I think that it may be in `v2.3.0`.
=> add full changelog link to `2.3.0` release

lib/dotenv/environment.rb
* Commit 7f82f73 introduced a backwards-incompatible change in the current API with respect to `Dotenv::Environment#intialize` by changing the method signature.
* Make the new parameter default to false to retain backwards compatibility.
* Similar changes were made for `Dotenv::Parser` in #338.
SEE: https://github.com/bkeepers/dotenv/pull/323
SEE: https://github.com/bkeepers/dotenv/pull/338
=> Backwards Compatible Dotenv::Environment

lib/dotenv.rb, spec/dotenv_spec.rb
Hi
I think it is useful to have an equivalent of `load!` method with a possibility to override any existing environment variables, hence this PR introduces `overload!` method.
=> Adding Dotenv.overload!

README.md
Reason for Change
=================
* The load hierarchy and what overrides what is confusing!
Changes
=======
* Add a table to help minimize confusion.
=> Clarify variable hierarchy in README.md

README.md, lib/dotenv.rb, spec/dotenv_spec.rb
Opening the PR for discussion around a new feature request. 
Exposes parsing logic as a public API to allow programmatic inspection of .env files without modifying `ENV`.
One such use case is for automated application setup to create/read/modify `.env` files prior to running the application for the first time. I found the need to dive into `Dotenv` internals to accomplish such a task while debugging installation scripts on a recent project and thought it would be useful to avoid relying on internal details.
=> Add Dotenv.parse method

.github/main.workflow
This adds a GitHub Actions workflow for code pushes.  I created a [Custom Action](https://github.com/cadwallion/publish-rubygems-action) that handles triggering release commands.  If a tag is pushed with a version, both the dotenv and dotenv-rails gems will be published to Rubygems.org.  Note: since Actions only supports 'push' events in the beta, you have to tag and specifically push the tag, instead of using `git push --tags` for this to work.
1. Bump the version, Commit
2. `git tag vX.Y.Z`
3. `git push origin vX.Y.Z`
4. Workflow will detect the push event was on a version tag, trigger release
Completes #367 
//cc @joelvh
=> Automate Rubygems Releases with Actions

lib/dotenv/cli.rb
This replaces the odd file parsing in the Dotenv::CLI with a proper OptionParser implementation that automatically handles converting the comma-separated list into an Array and with proper flag support.
This also adds --version and --help flag support to the CLI, since it's practically free with OptionParser.
Completes #371 
/cc @olleolleolle
```
octobox dotenv (help) ./bin/dotenv --help
Usage: dotenv [options]
-f FILES                         List of env files to parse
-h, --help                       Display help
-v, --version                    Show version
```
=> Improvements to dotenv CLI

lib/dotenv/cli.rb, spec/dotenv/cli_spec.rb
This adds a flag matcher in addition to OptionParser that ensures that we only parse the flags leading up to the command we attempt to execute.  
Resolves #375
=> Fixes regression with CLI experience

lib/dotenv/cli.rb, spec/dotenv/cli_spec.rb
This removes the regular expression logic and splitting out of the parser_args vs exec_args in favor of using OptionParser.order! which will not complain about unknown flags because order will stop at the first unknown argument.
This is a dramatic improvement to the CLI code clarity.
Closes #381 
Thanks to @bensherman for pairing up to better understand what was going on under the hood, and finding the .order! method. 
/cc @walro
=> Clean up the option parser

lib/dotenv/cli.rb
i think modifiy `unless -> if` easy to understand.
my english is weak...
i`m sorry!
=> modifiy conditional branch

lib/dotenv/rails.rb
If `Rails` is already loaded by the time `dotenv` is loaded, the
configuration block is executed immediately, prior to the rest of the
`Railtie` class being finished. Fixes https://github.com/bkeepers/dotenv/issues/297
=> Fixes load order issue.

lib/dotenv/rails.rb
along the lines of https://github.com/bkeepers/dotenv/pull/241, this will fix tasks for running parallel specs using the https://github.com/grosser/parallel_tests gem. (this will also match the `parallel:spec[...]` syntax.)
=> fix for parallel spec tasks initializing in development

README.md, lib/dotenv/cli.rb, lib/dotenv/template.rb, spec/dotenv/cli_spec.rb
Templates can be checked in and will show the environment variables used but wont show the values
I love using this package while writing demos at Stripe. However every now and then I miss a variable in my README.md or a handcrafted .env.template. 
This adds a flag to the cli so that you can point it at any .env file and safely create a template from it that doesn't include any of your keys. :)
=> Adding support for creating templates from .env files.

lib/dotenv/cli.rb
This reverts commit 00e14aa186917b557a6ccb2c08ea89e56f3faad1.
Reason: The pure Ruby doesn't have `Array#present?`. So this cause `NoMethodError` when using dotenv without Rails.
```
$ dotenv -t .env
Traceback (most recent call last):
3: from /bin/dotenv:23:in `<main>'
2: from /bin/dotenv:23:in `load'
1: from /lib/ruby/gems/2.5.0/gems/dotenv-2.7.3/bin/dotenv:4:in `<top (required)>'
/lib/ruby/gems/2.5.0/gems/dotenv-2.7.3/lib/dotenv/cli.rb:25:in `run': undefined method `present?' for []:Array (NoMethodError)
Did you mean?  prepend
```
=> Fix `NoMethodError` when using dotenv without Rails.

lib/dotenv/parser.rb, spec/dotenv/parser_spec.rb
We have in our `.env`-file an entry with `=` as separator followed by a `\s` and a quoted value including `#` in this way:
```
SECRET_PASSWORD              = 'foo#bar234#'
```
Parsing it leads to the unfortunate cutting after the `#`:
```
env("SECRET_PASSWORD              = 'foo#bar234#'")
=> {"SECRET_PASSWORD"=>"'foo"}
```
This fix will let it parse correctly:
```
env("SECRET_PASSWORD              = 'foo#bar234#'")
=> {"SECRET_PASSWORD"=>"foo#bar234#"}
```
=> Adds specs and fix for \s after separator

dotenv-rails.gemspec
My rails application (blog) works with this patch.
=> Support Rails < 6.2

lib/dotenv/rails.rb, spec/dotenv/rails_spec.rb
Add a `Dotenv::Railtie.overload` method, which allows to overload environment variables in Rails context.
Resolves #401.
=> Add a Dotenv::Railtie.overload method.

lib/dotenv/template.rb, spec/dotenv/cli_spec.rb
Template treats every line as a variable declaration. Add conditions to ensure only variable declarations are templated. Blank lines and comments are left as-is.
=> Fix template (-t) handling of blank lines and comments

lib/dotenv/rails.rb
This is a followup of #241 and brings the `dotenv-rails` environment
assigning hack in line with the [logic rails uses when the
`test_unit/railtie` is loaded][1].
This is a breaking change for all non `test-unit` users, but brings the
behavior of `dotenv-rails` in line across all uses of `rake test`, `rake
rspec`, `rspec` and `rake`.
Before this change `dotenv-rails` loaded different env files when using
a rails application with `rspec` for tests. `rake spec` was covered by
the previous logic and set the RAILS_ENV to test. Only running `rake`
(which invokes rspec by default) wasn't covered and thus loaded first
the development env files and later the test env.
[1]: https://github.com/rails/rails/blob/6-0-stable/railties/lib/rails/test_unit/railtie.rb#L5-L7
=> Set RAILS_ENV to test when executing the default rake task

lib/dotenv/parser.rb, spec/dotenv/parser_spec.rb
Thank you for this handy gem. We use it regularly.
When using Ruby's shellwords library to escape values, the following env file is created.
```
export FOO=one\ two
```
Quotes cannot be used around those values, otherwise the backslash is considered a literal.
```
$ export FOO="one\ two"
$ echo $FOO
one\ two
$ export FOO=one\ two
$ echo $FOO
one two
```
This PR updates the code to correctly unescape characters when quotes are not used
The parse_value method had to be refactored to keep Rubocop happy.
=> feat: unescape escaped characters when value is not quoted

.github/workflows/ci.yml, Gemfile
Adds Ruby 3 to the build matrix, and removes conditionals for old versions of mri and rbx
=> Update supported platforms

lib/dotenv/template.rb, spec/dotenv/cli_spec.rb
Fixed `export` commands being repeated in templated values. 
Current: 
`export FOO=BAR` templated as `export FOO=export FOO`. 
Fix:
`export FOO=BAR`  templated as `export FOO=FOO`
=> Fix template (-t) handling of export declarations

README.md
Loading dotenv in production raise error for the obvious reason that we install it only for development and test environment. So I think this instruction should be included in the readme file so that we load it only if we are in the desired environments.
=> Update instruction for loading dotenv

lib/dotenv.rb, spec/dotenv/rails_spec.rb, spec/dotenv_spec.rb, spec/fixtures/important.env
```bash
$ cat Gemfile
source "https://rubygems.org"
ruby File.read("#{File.dirname(__FILE__)}/.ruby-version")
gem "pry"
group :development, :test do
gem "dotenv"
end
$ cat Gemfile.lock
GEM
remote: https://rubygems.org/
specs:
coderay (1.1.3)
dotenv (2.8.1)
method_source (1.0.0)
pry (0.13.1)
coderay (~> 1.1)
method_source (~> 1.0)
PLATFORMS
ruby
DEPENDENCIES
dotenv
pry
RUBY VERSION
ruby 3.1.2p20
BUNDLED WITH
2.3.16
$ cat bin/scripts/console
#!/usr/bin/env ruby
require "pry"
Pry.start
$ cat .env.important
EXAMPLE_VAR=5678
$ cat .env.most.important
EXAMPLE_VAR=1234
$ bundle exec dotenv -o -f ".env.most.important,.env.important" ./bin/scripts/console
[1] pry(main)> ENV["EXAMPLE_VAR"]
=> "5678"
[2] pry(main)> exit
$ bundle exec dotenv -o -f ".env.important,.env.most.important" …
```
=> fix: always respect file importance order

.standard.yml, lib/dotenv.rb, lib/dotenv/environment.rb, lib/dotenv/parser.rb, lib/dotenv/substitutions/command.rb, lib/dotenv/substitutions/variable.rb, spec/dotenv/environment_spec.rb, spec/dotenv/parser_spec.rb, spec/dotenv_spec.rb
This refactors `load`, `load!`, `overload`, `overload!`, and `parse`. There should be no user-facing changes.
=> Refactor `Dotenv.load` and friends

README.md, dotenv-rails.gemspec, dotenv.gemspec, lib/dotenv.rb, lib/dotenv/load.rb, lib/dotenv/rails-now.rb, lib/dotenv/rails.rb, spec/dotenv/rails_spec.rb, spec/spec_helper.rb
This refactors the Rails integration, and includes it in the `dotenv` gem by default.
- Renames `Dotenv::Railtie` => `Dotenv::Rails`
- Adds `Dotenv::Rails.files`, which can be mutated to change which files are loaded
- Adds `Dotenv::Rails.overwrite = true` to overwrite existing ENV variables
I thought about deprecating the `dotenv-rails` gem, but for now I can just keep releasing it as an empty gem with a dependency on `dotenv`.
=> Include Rails integration in `dotenv` gem and refactor

README.md, lib/dotenv.rb, lib/dotenv/cli.rb, lib/dotenv/rails.rb, spec/dotenv/environment_spec.rb, spec/dotenv/parser_spec.rb, spec/dotenv/rails_spec.rb, spec/dotenv_spec.rb
Preferred use: `Dotenv.load files, overwrite: true`
`Dotenv.overload` and `Dotenv.overload!` are still around, but not documented.
=> Consistently use "overwrite" in place of "overload" and "override"

lib/dotenv/rails.rb
Set env to `test` for `rake test` (replacement for #441).
This also adds a log message to explain what was loaded to hopefully make it easier for people to diagnose issues in the future.
```
dotenv loaded ENV from .env.development and .env
```
Fixes #439
=> Rake test rails env

.github/workflows/ci.yml, Gemfile, dotenv-rails.gemspec, dotenv.gemspec, lib/dotenv/environment.rb, lib/dotenv/rails.rb
- Require Ruby `>= 3.0` and Rails `>= 6.1`. Those using EOL versions can lock dotenv to `~> 2.0`
- Add Rails 6.1, 7.0, and 7.1 to build matrix.
=> Require Ruby 3.0 and Rails 7.1

lib/dotenv.rb, lib/dotenv/diff.rb, lib/dotenv/log_subscriber.rb, lib/dotenv/rails.rb, lib/dotenv/replay_logger.rb, spec/dotenv/diff_spec.rb, spec/dotenv/log_subscriber_spec.rb, spec/dotenv/rails_spec.rb, spec/dotenv_spec.rb
This adds logging in Rails to any `ENV` changes performed by dotenv.
```console
$ rails console
…
$ tail log/development.rb
```
```console
$ rails console
> Dotenv.save
…
> ENV.update("PWD" => "/tmp", "NEW_VAR" => "foo")
…
> Dotenv.restore
…
$ tail log/development.rb
```
cc #472
=> Log all changes to ENV

lib/dotenv.rb, lib/dotenv/autorestore.rb, lib/dotenv/diff.rb, lib/dotenv/environment.rb, lib/dotenv/log_subscriber.rb, spec/dotenv/diff_spec.rb, spec/dotenv/environment_spec.rb, spec/dotenv/log_subscriber_spec.rb, spec/dotenv_spec.rb
This fixes an issue with #472 when running Rails tests with `parallelize`. Since `ENV` is global state, modifications are not thread safe. This will raise an error if calling `Dotenv.restore` outside of `Thread.main`, and adds `Dotenv.modify` for a threadsafe way to modify `ENV`.
```ruby
Dotenv.modify(MYVAR: "new value") do
assert_equal "new value", ENV["MYVAR"]
end
```
Note that the block passed to `#modify` is synchronized in a semaphore, so threads calling it will execute serially.
This PR also refactors `Dotenv::Diff` introduced in #473 and uses it to save/restore.
=> Handle thread safety for Dotenv.restore, Add Dotenv.modify

README.md, lib/dotenv/rails.rb, spec/dotenv/rails_spec.rb
This will disable autorestore if `ClimateControl` or `IceAge` constants are defined.
cc #482
=> Disable autorestore if using climate_control or ice_age

lib/dotenv/rails.rb, spec/dotenv/rails_spec.rb
In v2, files were joined with `Rails.root` during the `before_configuration` callback. #468 refactored the list of files to be configurable, but caused the paths to be joined with `Rails.root` at the time of app initialization (before Rails.root is set).
@mvz can you try this branch out and let me know if it fixes the issue you were running into?
cc https://github.com/bkeepers/dotenv/discussions/476#discussioncomment-8464531
=> Join files to Rails.root at load time

lib/dotenv/rails.rb
This adds a manual check for the Rails version before loading the railtie.
Fixes #480
=> Manually check optional Rails dependency version

lib/dotenv/rails.rb, spec/dotenv/rails_spec.rb
Fixes https://github.com/bkeepers/dotenv/pull/484#discussion_r1491359895 
cc @lucasmazza
=> Restore ability to mutate Dotenv::Rails.files

lib/dotenv-rails.rb, lib/dotenv/rails.rb
See issue https://github.com/bkeepers/dotenv/issues/490.
=> Solve circular require warning.

lib/dotenv/rails.rb, spec/dotenv/rails_spec.rb
Fixes #488
- fix: call `tagged` from an existing tagged logger
- fix: correctly uninitialize logger between runs
=> Use tagged logger already configured on Rails

lib/dotenv/replay_logger.rb, spec/dotenv/rails_spec.rb
Thanks to @zspencer for pointing out in #487 that the current ReplayLogger could cause exceptions in some circumstances. This refactors it to extend `Logger` so it will behave like a real logger.
=> Refactor ReplayLogger to extend Logger

lib/dotenv/template.rb, spec/dotenv/cli_spec.rb
I'm noticing that multi-line variables aren't properly templated. This input:
```
FOO=BAR
FOO2="BAR2
BAR2
BAR2
BAR2"
FOO3=BAR3
```
produces this output:
```
FOO=FOO
FOO2=FOO2
BAR2
BAR2
BAR2"
FOO3=FOO3
```
My expectation is that it would instead produce this output:
```
FOO=FOO
FOO2=FOO2
FOO3=FOO3
```
=> Fix template (-t) handling of multi-line variables

lib/dotenv.rb, spec/dotenv_spec.rb
This adds a guard against calling `Dotenv.restore` without having previously called `Dotenv.save`.
This should fix #500, but I can't reproduce that exact scenario.
=> Guard against restore being called with no previously saved state

README.md
=> Spell out 'FILENAME' in readme

dotenv.gemspec
By providing a 'changelog_uri' in the metadata of the gemspec a 'Changelog' link will be shown on https://rubygems.org/gems/dotenv which makes it quick and easy for someone to check on the changes introduced with a new version.
Details of this functionality can be found on https://guides.rubygems.org/specification-reference/
=> Provide a 'Changelog' link on rubygems.org/gems/dotenv

lib/dotenv/rails.rb
This PR offers the auto-fix for the a standardrb violation.
This gets us back to green.
Seen when [cf5dcf7](https://github.com/bkeepers/dotenv/commit/cf5dcf7e6e9ba90ad5cbee0a7467271bd6a4f1b5) ran its build.
=> cleanup: Run standard:fix

lib/dotenv/rails.rb, spec/dotenv/rails_spec.rb
This makes it possible for the user to selectively use Spring on a command to command basis
Fixes https://github.com/bkeepers/dotenv/issues/510
=> Only use Spring if already loaded

lib/dotenv/rails.rb, spec/dotenv/rails_spec.rb
An exception occurs when invoking the rake task via ./bin/rails.
```
bin/rails aborted!
NoMethodError: undefined method `watch' for Spring:Module (NoMethodError)
Spring.watch event.payload[:env].filename if Rails.application
^^^^^^
.bundle/ruby/3.2.0/gems/dotenv-3.1.3/lib/dotenv/rails.rb:16:in `block in <main>'
```
When using `./bin/rails`, 'spring/client' is loaded, but 'spring/watcher', which is unnecessary for the client-side, is not required.
This PR follows up on https://github.com/bkeepers/dotenv/pull/511/ and fixes exception.
=> follow-up https://github.com/bkeepers/dotenv/pull/511/

Gemfile, benchmark/parse_ips.rb, benchmark/parse_profile.rb, lib/dotenv/parser.rb, lib/dotenv/substitutions/command.rb, lib/dotenv/substitutions/variable.rb
Thanks for the helpful gem!
While profiling the startup time for a large Rails app that's manually invoking `Dotenv.load` very early on in the boot process in order to get access to envvars ASAP, I noticed that the subsequent `Dotenv.load` being automatically called by this gem's provided railtie was taking an unusual amount of time to complete. The time was mostly being spent in the variable substitution module, on this line:
```ruby
combined_env = overwrite ? ENV.to_h.merge(env) : env.merge(ENV)
```
Since `ENV` had already been loaded up with ~2,000 extra variables from the first run of dotenv, this hash merge is not a trivially cheap operation and it added up being run when parsing each line. 
From what I understand, the purpose of that line is to build a lookup table that gives …
=> Optimize parser by removing repeated hash merges

lib/dotenv/parser.rb, spec/dotenv/parser_spec.rb
Part of the optimization in #515 was to skip parsing variables that were already defined. But that had the side-effect of not returning them in the resulting hash. This adds a test for this behavior and restores it.
Fixes #518
=> Restore previous parser behavior of returning existing variables

.github/workflows/ci.yml
I get tired of having to manually update Ruby/Rails versions in the GitHub Actions config, so this is an experiment to automate it by fetching the currently supported versions from endoflife.date.
=> Generate build matrix from endoflife.date

Changelog.md, lib/dotenv/parser.rb, lib/dotenv/version.rb, spec/dotenv/parser_spec.rb
#517 had an over-eager regex that removes repeated linebreaks when normalizing line endings. This adds a tests for that scenario and fixes #522.
=> Fix issue with repeated linebreaks when normalizing line endings

README.md
The former description led to the conclusion that the most important file should be placed last. The change in the description should make this clearer.
=> Clarify order of configuration files for flag -f

dotenv-rails.gemspec
A changelog_uri value was added to the dotenv.gemspec in [PR#506](https://github.com/bkeepers/dotenv/pull/506). This PR adds it to dotenv-rails.gemspec as well so that the 'Changelog' link will be shown on https://rubygems.org/gems/dotenv-rails
=> Provide a 'Changelog' link on rubygems.org/gems/dotenv-rails

lib/dotenv.rb
ignore when .env is a folder the same way when .env file doest exists
=> fix crash when .env is a folder
